version: "3.7"

services:
  fullstack:
    build:
      context: .
      dockerfile: Dockerfile
      # reference docker target
      target: fullstack
    container_name: fullstack
    restart: unless-stopped
    entrypoint: ./main.bin --dir database serve --http=0.0.0.0:${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - database:/app/database
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:${BACKEND_PORT}/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

volumes:
  database:
