version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      # reference docker target
      target: go-pipeline
      args:
        PROJECT: backend
    restart: unless-stopped
    entrypoint: ./main --dir database serve --http=0.0.0.0:${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - database:/app/database
      - frontend-public:/app/public:ro
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:${BACKEND_PORT}/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      # reference docker target
      target: node-pipeline-static
      args:
        PROJECT: frontend
    volumes:
      - frontend-public:/app:rw

volumes:
  database:
  frontend-public:
